import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import CreatePost from "~/components/CreatePost";
import AllPosts from "~/components/AllPosts";

const Home: NextPage = () => {
  const { data, isLoading } = api.post.getAllPost.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-h-screen  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-white">Create Post</h1>
        <CreatePost />
        <hr />
        {isLoading && <p className="text-white">Loading...</p>}
        {data &&
          data?.length > 0 &&
          data.map((post) => <AllPosts post={post} key={post._id as string} />)}
      </main>
    </>
  );
};

export default Home;
