import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import CreatePost from "~/components/CreatePost";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-h-screen  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-white">Create Post</h1>
        <CreatePost />
      </main>
    </>
  );
};

export default Home;
